This files creates the training and test datasets for all other notebooks and scripts to reuse. This is the file I would typically use for an exploratory analysis.

In [13]:
import pickle
import helpsk as hlp
import numpy as np
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split

%matplotlib inline

# Load Data

In [2]:
#https://www.openml.org/d/31
credit_g = fetch_openml('credit-g', version=1)
credit_data = credit_g['data']
credit_data['target'] = credit_g['target']
print(credit_data.shape)

del credit_g

(1000, 21)


In [3]:
## Create Missing Values
credit_data['duration'].iloc[0:46] = np.nan
credit_data['checking_status'].iloc[25:75] = np.nan
credit_data['credit_amount'].iloc[10:54] = 0

/Users/shanekercheval/opt/anaconda3/envs/python-examples/lib/python3.9/site-packages/pandas/core/indexing.py:1732: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)


In [4]:
hlp.pandas.numeric_summary(credit_data, return_style=True)

In [5]:
hlp.pandas.non_numeric_summary(credit_data, return_style=True)

# Training and Test Data

In [6]:
y_full = credit_data['target']
X_full = credit_data.drop(columns='target')

del credit_data

In [7]:
hlp.pandas.value_frequency(series=y_full)

Frequency  Percent
good        700      0.7
bad         300      0.3

In [8]:
y_full[0:10]

0    good
1     bad
2    good
3    good
4     bad
5    good
6    good
7    good
8    good
9     bad
Name: target, dtype: category
Categories (2, object): ['good', 'bad']

In [11]:
from sklearn.preprocessing import label_binarize
y_full = label_binarize(y_full, classes=['bad', 'good']).flatten()

In [12]:
y_full[0:10]

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 0])

In [14]:
# save the full dataset for creating the fine model
with open('X_full.pkl', 'wb') as handle:
    pickle.dump(X_full, handle)

with open('y_full.pkl', 'wb') as handle:
    pickle.dump(y_full, handle)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X_full, y_full, test_size=0.2, random_state=42)
del X_full, y_full

In [16]:
print(X_train.shape)
print(len(y_train))

print(X_test.shape)
print(len(y_test))

(800, 20)
800
(200, 20)
200


In [17]:
np.unique(y_train, return_counts=True)

(array([0, 1]), array([241, 559]))

In [18]:
np.unique(y_train, return_counts=True)[1] / np.sum(np.unique(y_train, return_counts=True)[1])

array([0.30125, 0.69875])

In [19]:
np.unique(y_test, return_counts=True)[1] / np.sum(np.unique(y_test, return_counts=True)[1])

array([0.295, 0.705])

In [20]:
import pickle

with open('X_train.pkl', 'wb') as handle:
    pickle.dump(X_train, handle)

with open('X_test.pkl', 'wb') as handle:
    pickle.dump(X_test, handle)

with open('y_train.pkl', 'wb') as handle:
    pickle.dump(y_train, handle)

with open('y_test.pkl', 'wb') as handle:
    pickle.dump(y_test, handle)

del X_test, y_test

# Exploratory

Typically I would do an exploratory analysis here.

In [21]:
X_train.head()

checking_status  duration                  credit_history    purpose  \
29              NaN       NaN              delayed previously   business   
535           >=200      21.0  critical/other existing credit  education   
695     no checking       6.0                   existing paid   used car   
557     no checking      21.0             no credits/all paid    new car   
836     no checking      12.0                   existing paid   radio/tv   

     credit_amount    savings_status employment  installment_commitment  \
29             0.0              <100        >=7                     3.0   
535         2319.0              <100         <1                     2.0   
695         1236.0       500<=X<1000     1<=X<4                     2.0   
557         5003.0  no known savings     1<=X<4                     1.0   
836          886.0  no known savings     1<=X<4                     4.0   

        personal_status other_parties  residence_since property_magnitude  \
29          male single          none              4.0  no known property   
535        male div/sep          none              1.0                car   
695         male single          none              4.0     life insurance   
557  female div/dep/mar          none              4.0     life insurance   
836  female div/dep/mar          none              2.0                car   

      age other_payment_plans housing  existing_credits      job  \
29   63.0                none     own               2.0  skilled   
535  33.0                none    rent               1.0  skilled   
695  50.0                none    rent               1.0  skilled   
557  29.0                bank     own               2.0  skilled   
836  21.0                none     own               1.0  skilled   

     num_dependents own_telephone foreign_worker  
29              1.0           yes            yes  
535             1.0          none            yes  
695             1.0          none            yes  
557             1.0           yes            yes  
836             1.0          none            yes

In [23]:
y_train[0:10]

array([0, 0, 1, 0, 1, 0, 1, 0, 0, 1])